# Generated by Django 5.1.1 on 2024-10-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_autor_created_by_libro_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='descripcion_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='descripcion_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='titulo_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='titulo_es',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
